import {env} from "cloudflare:workers";
const encoder=new TextEncoder();
export function db(){return (env as any).DB as D1Database;}
function setting(key:string){const value=(env as any)[key];if(typeof value!=="string"||!value)throw Error("Admin access not configured");return value;}
export async function digest(value:string){return Array.from(new Uint8Array(await crypto.subtle.digest("SHA-256",encoder.encode(value))),v=>v.toString(16).padStart(2,"0")).join("");}
export function equal(a:string,b:string){let difference=a.length^b.length;for(let i=0;i<Math.max(a.length,b.length);i++)difference|=(a.charCodeAt(i)||0)^(b.charCodeAt(i)||0);return difference===0;}
export async function verify(username:string,password:string){const key=await crypto.subtle.importKey("raw",encoder.encode(password),"PBKDF2",false,["deriveBits"]);const salt=Uint8Array.from(atob(setting("ADMIN_PASSWORD_SALT")),c=>c.charCodeAt(0));const bits=await crypto.subtle.deriveBits({name:"PBKDF2",salt,iterations:100000,hash:"SHA-256"},key,256);const hash=btoa(String.fromCharCode(...new Uint8Array(bits)));return equal(hash,setting("ADMIN_PASSWORD_HASH"))&&equal(username,setting("ADMIN_USERNAME"));}
export function local(request:Request){return ["localhost","127.0.0.1"].includes(new URL(request.url).hostname);}
export function cookieName(request:Request){return local(request)?"pf_admin_local":"__Host-pf_admin";}
export function token(request:Request){const name=cookieName(request);return request.headers.get("cookie")?.split(";").map(c=>c.trim()).find(c=>c.startsWith(name+"="))?.slice(name.length+1)||"";}
export function cookie(request:Request,value:string,age=7200){return `${cookieName(request)}=${value}; Path=/; HttpOnly; SameSite=Strict; Max-Age=${age}${local(request)?"":"; Secure"}`;}
export function sameOrigin(request:Request){return request.headers.get("origin")===new URL(request.url).origin;}
export async function authenticated(request:Request){const raw=token(request);if(!/^[a-f0-9]{64}$/.test(raw))return false;const row=await db().prepare("SELECT expires FROM admin_sessions WHERE token_hash = ? AND expires > ?").bind(await digest(raw),Date.now()).first();return !!row;}
export async function attempt(request:Request){const ip=request.headers.get("cf-connecting-ip")||request.headers.get("oai-authenticated-user-id")||"shared";const key=await digest(setting("ADMIN_RATE_KEY")+ip),window=Math.floor(Date.now()/600000);await db().prepare("INSERT INTO admin_attempts (key,window,count) VALUES (?,?,1) ON CONFLICT(key) DO UPDATE SET count=CASE WHEN admin_attempts.window=excluded.window THEN admin_attempts.count+1 ELSE 1 END,window=excluded.window").bind(key,window).run();const row=await db().prepare("SELECT count FROM admin_attempts WHERE key=?").bind(key).first<{count:number}>();return {key,allowed:!!row&&row.count<=5};}
export async function session(){const raw=Array.from(crypto.getRandomValues(new Uint8Array(32)),v=>v.toString(16).padStart(2,"0")).join("");await db().batch([db().prepare("DELETE FROM admin_sessions WHERE expires < ?").bind(Date.now()),db().prepare("INSERT INTO admin_sessions (token_hash,expires) VALUES (?,?)").bind(await digest(raw),Date.now()+7200000)]);return raw;}
export function json(body:unknown,status=200,extra:HeadersInit={}){return Response.json(body,{status,headers:{"Cache-Control":"no-store","X-Content-Type-Options":"nosniff",...extra}});}
